---
# Django Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        # REPLACE THIS WITH YOUR ACTUAL DJANGO DOCKER IMAGE
        image: syacode/django-app:9eeaa47fdefd630db6b76d94025b3929244524fe
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "mysql-service" # This matches the name of the MySQL Service above
        - name: DB_PORT
          value: "3306"
        envFrom:
        - secretRef:
            name: mysql-secret
---
# Django Service (Expose to the outside world)
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: LoadBalancer # Use NodePort if running locally on Minikube
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: django-app
