name: Checkov Security Scan

# Trigger the workflow on pushes and pull requests to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v6

      # Step 2: Run the Checkov scan
      - name: Run Checkov against infrastructure code
        uses: bridgecrewio/checkov-action@master
        with:
          # Point Checkov to the directory you want to scan (usually the root '.')
          directory: .
          
          # Optional: Specify a framework (e.g., terraform, cloudformation, kubernetes)
          # framework: terraform 
          
          # Optional: Set to true if you want the pipeline to pass even if Checkov finds violations
          # soft_fail: true
